site_name: 天津大学数学学院本科生指北
site_url: https://jiyouhai.github.io/tju-math-guide/
site_author: jiyouhai
site_description: 一些关于天大，关于数学的信息和资料，你可能需要会需要他们
repo_name: tju-math-guide
repo_url: https://github.com/jiyouhai/tju-math-guide/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.view
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - social
  - search
extra:
  analytics:
    provider: google
    property: G-DYRB5HD31Q
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jiyouhai
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100082717939442&mibextid=9R9pXO
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: |
  &copy; 2023 <a href="https://github.com/jiyouhai"  target="_blank" rel="noopener">jiyouhai</a>
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - 前言: 'foreword.md'
    - 贡献者说: 'forcontributors.md'
    - 数学类专业课程: 'professional_courses.md'
    - 各专业专业课程: 'various_majors.md'
    - 未来可能的答案:
        # - 未来可能的答案/index.md
        - 抽象代数: '未来可能的答案/abstractalgebra.md'
        - 数学分析: '未来可能的答案/mathmaticalanalysis.md'
